import { ReactNode } from 'react'
import Head from 'next/head'
import Nav from './Nav'

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-base-100 text-base-content">
      <Head>
        <title>{process.env.NEXT_PUBLIC_SITE_TITLE}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Nav />
      <main className="flex flex-col items-center justify-center w-full flex-1 p-2 md:px-20 text-center">
        {children}
      </main>
      <footer className="flex items-center justify-center w-full h-24 border-t">
        <a
          className="pl-1 link link-primary link-hover"
          href="https://github.com/renft721"
          target="_blank"
          rel="noreferrer"
        >
          @renft721
        </a>
        <span className="pl-1"> | </span>
        <a
          className="pl-1 link link-primary link-hover"
          href="https://github.com/MarioScalabrino"
          target="_blank"
          rel="noreferrer"
        >
          @MarioScalabrino
        </a>
        <span className="pl-1"> | </span>
        <a
          className="pl-1 link link-primary link-hover"
          href="https://github.com/cito-lito"
          target="_blank"
          rel="noreferrer"
        >
          @cito-lito
        </a>
        <span className="pl-1"> | </span>
        <a
          className="pl-1 link link-primary link-hover"
          href="https://github.com/thalandor"
          target="_blank"
          rel="noreferrer"
        >
          @thalandor
        </a>
      </footer>
    </div>
  )
}
